name: deploy

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install

    - name: Build and deploy to GitHub Pages
      run: |
        npm run build
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push --force --quiet "https://github.com/${{ github.repository }}" HEAD:gh-pages

    - name: GitHub Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
