# File name: deploy.yml
# Date: 03 May 2025
# Author: Kyle McColgan
# Description: The GitHub Actions and Pages deployment workflow for the timer web app.

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment.
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Step 3: Install npm dependencies.
      - name: Install npm dependencies
        run: npm install

      # Step 4: Build the project and run the build script.
      - name: Run build
        run: npm run build               which includes rendering static files.

      # Step 5: Deploy to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
